### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mistakevin** [AustinCodingAcademy/intermediate-textbook#1]
- [x] Install Guide
- [x] Prework
- [x] Syllabus
- [x] App Guides
  - [x] Pig Latin
  - [x] Rock Paper Scissors
  - [x] Tic Tac Toe
  - [x] Towers of Hanoi
  - [x] Mastermind
  - [x] Checkers
  - [x] Tic Tac Toe (jQuery)
  - [x] Towers of Hanoi (jQuery)
  - [x] Todo (jQuery)
  - [x] Address Book (jQuery/AJAX)
  - [x] Gist Blog

- [x] Lessons
  - [x] Lesson Zero (Github/SSH Keys/Node)
  - [x] Lesson One (Javascript Syntax/Primitives)
  - [x] Lesson Two (Conditionals/Functions)
  - [x] Lesson Three (Scope/Ternary/Arrays)
    - [x] Remove Prompt Details
  - [x] Lesson Four (Arrays/Objects) 
    - [x] Change Associative Arrays to Objects
  - [x] Lesson Five (Operators/Loops)
  - [x] Lesson Six (Object Oriented Programming)
  - [x] Lesson Seven (Serving/jQuery/Callbacks)
  - [x] Lesson Eight (jQuery Methods)
  - [x] Lesson Nine (Preventing Default Event/jQuery UI)
  - [x] Lesson Ten (AJAX/JSON)
